version: '3'
services:
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    environment:
      - REDIS_PASSWORD=secretpassword
volumes:
 redisdata:
